export interface ReportSAccess {
    UserName: string;
    UserAccessStatus: string;
    IMPS: boolean;
    CTO: boolean;
    AutomatedCLR: boolean;
    StageGate: boolean;
    NPS : boolean;
    LessonsLearnt: boolean;
    CapacityTracker: boolean;
    CycleTime: boolean;
    ELTReport: boolean;
    C_Hierarchy: boolean;
    C_HierarchyEdits : boolean;
    MarketCommentsEdit : boolean;
    ResourceUtilization: boolean;
    PerformanceAnalysis : boolean;
    SteeringCommittee : boolean;
    SteeringCommittee_icon : string;
    SteeringCommitteeEdits : boolean;
    SteeringCommitteeEdits_icon : string;
    NPSAdmin : boolean;
    NPSClientInfo : boolean;
    NPSEdit : boolean;
    DigitalReport : boolean;
    PerformanceAnalysis_icon : string;
    NPSAdmin_icon : string;
    NPSClientInfo_icon : string;
    NPSEdit_icon : string;
    DigitalReport_icon : string;
    IMPS_icon: string;
    MarketCommentsEdit_icon : string;
    CTO_icon: string;
    AutomatedCLR_icon: string;
    StageGate_icon: string;
    NPS_icon : string;
    LessonsLearnt_icon: string;
    CapacityTracker_icon: string;
    CycleTime_icon: string;
    ELTReport_icon: string;
    C_Hierarchy_icon: string;
    C_HierarchyEdits_icon : string;
    CLREdits_icon : string;
    MarketReport_icon : string;
    ResourceUtilization_icon : string;
    UserStatus: string;
    Prospect: boolean;
    InsertedOn: Date;
    InsertedOn_s: String;
    UpdatedOn_s: String;
    UpdatedBy: string;
    UpdatedOn: Date;
    MarketReport : boolean;
    CLREdits : boolean;
    Notifications : number;
    AccountStatus : string;
    UID: string;
    AutomatedCLRStatus: string;
    AutomatedCLRRequesstedOn?: any;
    AutomatedCLRApporvedBy: string;
    AutomatedCLRApporvedOn?: any;
    CLREditsStatus: string;
    CLREditsRequesstedOn?: any;
    CLREditsApporvedBy: string;
    CLREditsApporvedOn?: any;
    MarketReportStatus: string;
    MarketReportRequesstedOn?: any;
    MarketReportApporvedBy: string;
    MarketReportApporvedOn?: any;
    CommentEditStatus : string;
    CommentEditRequesstedOn? : any;
    CommentEditApporvedBy : string;
    CommentEditApporvedOn? : any;
    CycleTimeStatus: string;
    CycleTimeRequesstedOn?: any;
    CycleTimeApporvedBy: string;
    CycleTimeApporvedOn?: any;
    ELTReportStatus: string;
    ELTReportRequesstedOn?: any;
    ELTReportApporvedBy: string;
    ELTReportApporvedOn?: any;
    IMPSStatus: string;
    IMPSRequesstedOn?: any;
    IMPSApporvedBy: string;
    IMPSApporvedOn?: any;
    CTOStatus: string;
    CTORequesstedOn?: any;
    CTOApporvedBy: string;
    CTOApporvedOn?: any;
    LLStatus: string;
    LLRequesstedOn?: any;
    LLApporvedBy: string;
    LLApporvedOn?: any;
    StageGateStatus: string;
    StageGateRequesstedOn?: any;
    StageGateApporvedBy: string;
    StageGateApporvedOn?: any;
    NPSStatus: string;
    NPSRequesstedOn?: any;
    NPSApporvedBy: string;
    NPSApporvedOn?: any;
    JobType : string;
}
export interface UserReportAccess {
    message: string;
    code: number;
    Data: ReportSAccess[];
    RevenueID : number;
}